=== JBearded/ClientProxy/src/main/resources/eproxy.dtd
<!ELEMENT eproxy (groupId,serverName,defaultHosts,extendInfo)>
        <!ELEMENT groupId (#PCDATA)>
        <!ELEMENT serverName (#PCDATA)>
        <!ELEMENT defaultHosts (#PCDATA)>
        <!ELEMENT extendInfo (property*)>
        <!ELEMENT property EMPTY>
<!ATTLIST property
        key CDATA #REQUIRED
        value CDATA #REQUIRED>

=== JBearded/ClientProxy/src/test/resources/redis-proxy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eproxy SYSTEM "eproxy.dtd">
<eproxy>
    <zookeeperHosts>172.25.51.12:2181</zookeeperHosts>
    <groupId>123</groupId>
    <serverName>redisServer</serverName>
    <defaultHosts>127.0.0.1:6380:1</defaultHosts>
    <extendInfo>
        <property key="maxActive" value="100"></property>
        <property key="maxIdle" value="100"></property>
        <property key="minIdle" value="20"></property>
        <property key="timeout" value="10000"></property>
    </extendInfo>
</eproxy>
